apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alphacar-main-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pogiri1207-a11y/alphacar.git
    targetRevision: release
    path: k8s/services/main-backend
  destination:
    server: https://kubernetes.default.svc
    namespace: alphacar
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
