apiVersion: apps/v1
kind: Deployment
metadata:
  name: alphacar-quote
  labels:
    app: quote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote
  template:
    metadata:
      labels:
        app: quote
    spec:
      containers:
      - name: quote
        # ğŸš€ ì¤‘ìš”: ì²˜ìŒì—” latestë‚˜ íŠ¹ì • ë²„ì „ì„ ì ì–´ë‘¡ë‹ˆë‹¤. (ì  í‚¨ìŠ¤ê°€ ì´ ë¶€ë¶„ì„ ìë™ìœ¼ë¡œ ê³ ì¹  ê²ë‹ˆë‹¤)
        image: 192.168.56.200:30002/alphacar/quote:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: alphacar-quote-svc
spec:
  selector:
    app: quote
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
