apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: alphacar-production
data:
  # Frontend 설정
  PORT: "8000"
  API_URL: "https://alphacar.192.168.56.161.nip.io/api"
  NEXT_PUBLIC_BASE_URL: "https://alphacar.192.168.56.161.nip.io"
  NEXT_PUBLIC_DOMAIN: "https://alphacar.192.168.56.161.nip.io"
  # SSL 인증서 경로 (필요시)
  # NODE_EXTRA_CA_CERTS: "/etc/ssl/certs/selfsigned.crt"

