apiVersion: v1
kind: ConfigMap
metadata:
  name: aichat-backend-config
  namespace: alphacar-production
data:
  PORT: "4000"
  SERVICE_NAME: "aichat-backend"
  # MongoDB 호스트 매핑
  MONGODB_PRIMARY: "192.168.0.201"
  MONGODB_SECONDARY_1: "192.168.0.201"
  MONGODB_SECONDARY_2: "192.168.0.201"

